language: node_js
node_js:
  - "14.18"
branches:
  only:
    - master
cache: yarn
script:
  - yarn
  - yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token: $FIREBASE_TOKEN
  edge: true
